name: Reset Develop Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch to reset (default: develop)"
        required: false
        default: "develop"

  schedule:
    - cron: "0 16 * * 0" # 每周日 24:00 (北京时间)

jobs:
  reset-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: Check last commit time
        if: github.event_name == 'schedule'
        id: check-commit
        run: |
          LAST_COMMIT_TIME=$(git log -1 --format=%ct)
          CURRENT_TIME=$(date +%s)
          TIME_DIFF=$((CURRENT_TIME - LAST_COMMIT_TIME))

          # 24 小时 = 86400 秒
          if [ "$TIME_DIFF" -lt 86400 ]; then
            echo "最近 24 小时内有提交，跳过重置"
            echo "SKIP_RESET=true" >> $GITHUB_ENV
          else
            echo "超过 24 小时无提交，执行重置"
            echo "SKIP_RESET=false" >> $GITHUB_ENV
          fi

      - name: Checkout main branch
        if: github.event_name == 'workflow_dispatch' || env.SKIP_RESET == 'false'
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Reset develop branch to main
        if: github.event_name == 'workflow_dispatch' || env.SKIP_RESET == 'false'
        run: |
          git checkout develop
          git reset --hard origin/main
          git push origin develop --force-with-lease
